#### datasets
datasets:
  n_workers: 8  # per GPU
  image_size: 299
  # v1 ./datasets/celebdf/celebdf_v1.txt
  root: ./datasets/celebdf/celebdf_v2.txt

  test:
    method: ~
    balance: False
    batch_size: 48

test:
  ckt_path: ./checkpoints/LVNet/checkpoint-13.pth.tar
  manual_seed: 1234

model:
  baseline: LVNet
